### ISSUE TITLE
Code release

### ISSUE THREAD

**Issue by yahooo-m** [workforai/UniLSeg#1]
Looking forward to it!

**Comment by yahooo-m** [comment]
When will your group release the code?

**Comment by yongliu20** [comment]
Thanks for your interest in our work! We are currently organizing the code and will make the code and weights public after internal reviews.

**Comment by FeiiYin** [comment]
What an incredible repo and amazing results!

**Comment by yongliu20** [comment]
Hi, we have released the general inference code. Thanks for your interest!
