### ISSUE TITLE
分割图像中的所有物体

### ISSUE THREAD

**Issue by BaiCHao12** [workforai/UniLSeg#10]
注意到在bpe_simple_vocab_16e6.txt.gz文件中没有发现object、all objects等提示词，想分割图像中的所有物体 提示词写什么

**Comment by yongliu20** [comment]
UniLSeg is designed to segment the target region based on the specific semantics of input text. The examples of segmenting all objects in the paper are achieved by combining different text inputs. Therefore, if you want to segment all the objects present in the image, you need to input different text prompts and combine the segmentation results.
