### ISSUE TITLE
AP for PartSeg

### ISSUE THREAD

**Issue by GloryyrolG** [workforai/UniLSeg#2]
Hi @workforai et al.,

thx for ur cvpr'24 work. for part segmentation, may i ask if the conventional ap metric (apart from iou in the paper) could be reported as well? looking fwd to the code & ckpt. thx & best,

**Comment by yongliu20** [comment]
Sorry, we haven't tested the segmentation results with AP metric. We may try to count that later if we have time. 
We have released the general inference code and UniLSeg-20 model weights (w/o finetuned on specified task dataset).
Welcome to try it!
