### ISSUE TITLE
I get poor result

### ISSUE THREAD

**Issue by Kaisor-Yuan** [workforai/UniLSeg#4]
Is there anything I need to adjust?
Why is the result I get different form yours so much?
![e94387e1e6219e0cb39d00dc5e87165](https://github.com/workforai/UniLSeg/assets/106362217/c3ba8d62-7b70-4904-98c2-9b9bda171cc5)
![f28538a7ad65851e8ce0a2100afab36](https://github.com/workforai/UniLSeg/assets/106362217/d1a9cd1c-e878-4904-929e-f24d16d1a525)

**Comment by yongliu20** [comment]
What's your input instruction? I also test this image with the released ckpt and get expected segmentation results. Just as the following shows (the instruction is "all light" and "all picture", respectively). Thus I think your input instruction or something is wrong. Besides, the visualization results in the paper are generated by UniLSeg-100 (pretrained on all SA-1B) and the model is finetuned on ADE20K as well. The released UniLSeg-20 without finetuned may perform a little worse.
![all_light](https://github.com/workforai/UniLSeg/assets/72915904/8a9a9fb6-583e-43f1-837d-da07a7e88639)
![all_picture](https://github.com/workforai/UniLSeg/assets/72915904/eb595bba-0105-4e59-a054-abcf433772a4)

**Comment by Kaisor-Yuan** [comment]
My instruction is all pillow

**Comment by yongliu20** [comment]
Here is the result I tested.
![all_pillow](https://github.com/workforai/UniLSeg/assets/72915904/5ab9a35a-af43-4a48-acfc-2fa27650067f)

**Comment by Kaisor-Yuan** [comment]
oh, sorry!
I find that when I download the UniLSeg-20, there is something wrong.
Now I get the satisfactory result.
Thanks for you great work!

**Comment by yongliu20** [comment]
Happy to hear that!
